theme: jekyll-theme-cayman

# Site settings
title: Trump Twitter Analysis
header-img: img/home-bg.jpg
email: rk878@georgetown.edu
description: "An analysis of Trumps tweets & comparison to U.S. extremist groups"
baseurl: ""
url: "https://raiyank.github.io/Trump-Twitter-Analysis/"
github_username:  RaiyanK

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["README.md"]

gems: [jekyll-paginate]
